# Generated by Django 4.2.5 on 2023-09-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=9)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=15)),
                ('grade', models.CharField(choices=[('1', 'Ensino básico incompleto'), ('2', 'Ensino básico completo'), ('3', 'Ensino médio incompleto'), ('4', 'Ensino médio completo'), ('5', 'Ensino superior incompleto'), ('6', 'Ensino superior completo')], max_length=1)),
            ],
        ),
    ]
